
version: '3.9'

networks:
  mynetwork:
    driver: bridge

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - mynetwork
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ./backend/queries_unilectin:/app/queries_unilectin
      - ./backend/queries_glyconnect:/app/queries_glyconnect
      - ./backend/queries_glystreem:/app/queries_glystreem



