#title: Q2.5 Complex Tetra Neutral
#comment: Tetra-Antennary Core + Sialylated (At least one NeuAc in ResidueSet)
#comment: glycoCT = "RES\n1b:x-dglc-HEX-1:5\n2b:x-dglc-HEX-1:5\n3b:x-dman-HEX-1:5\n4b:x-dman-HEX-1:5\n5b:x-dglc-HEX-1:5\n6b:x-dglc-HEX-1:5\n7b:x-dman-HEX-1:5\n8b:x-dglc-HEX-1:5\n9b:x-dglc-HEX-1:5\n10s:n-acetyl\n11s:n-acetyl\n12s:n-acetyl\n13s:n-acetyl\n14s:n-acetyl\n15s:n-acetyl\nLIN\n1:1o(-1+1)2d\n2:2o(-1+1)3d\n3:3o(-1+1)4d\n4:4o(-1+1)5d\n5:4o(-1+1)6d\n6:3o(-1+1)7d\n7:7o(-1+1)8d\n8:7o(-1+1)9d\n9:1d(2+1)10n\n10:2d(2+1)11n\n11:5d(2+1)12n\n12:6d(2+1)13n\n13:8d(2+1)14n\n14:9d(2+1)15n"

PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX modl: <https://archive.org/services/purl/domain/modular_ontology_design_library/>
PREFIX glystreem: <https://glyconnect.expasy.org/rdf/structures#>
SELECT DISTINCT ?glycanid
WHERE {
   ?glycan <https://glyconnect.expasy.org/rdf/structures#hasResidueSet> ?resSet .
   FILTER NOT EXISTS {?resSet ^modl:bagitemOf/glystreem:composition "NeuAc" .}
   ?glycan <https://glyconnect.expasy.org/rdf/structures#id> ?glycanid .
   ?var10 <https://archive.org/services/purl/domain/modular_ontology_design_library/bagitemOf> ?resSet .
   ?var21 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var13 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var15 .
   ?var16 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var18 .
   ?var18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var17 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var16 .
   ?var4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var10 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var1 .
   ?var6 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var13 <https://glyconnect.expasy.org/rdf/structures#composition> "Hex"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var7 <https://glyconnect.expasy.org/rdf/structures#baseName> "dman-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var4 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var10 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var14 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var13 .
   ?var13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var16 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var12 .
   ?var16 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var17 .
   ?var5 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var23 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var15 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var13 .
   ?var14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var22 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var14 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var21 .
   ?var20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var21 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var21 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var11 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var9 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var16 <https://glyconnect.expasy.org/rdf/structures#composition> "Hex"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var8 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var12 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var11 .
   ?var9 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var12 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var16 .
   ?var13 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var12 .
   ?var23 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var13 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var4 .
   ?var6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var1 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var24 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var10 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var11 .
   ?var19 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var22 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var22 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var10 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var19 .
   ?var16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var6 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var12 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var13 .
   ?var18 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var11 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var2 .
   ?var24 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var13 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var14 .
   ?var23 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var16 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var7 .
   ?var3 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#ResidueRoot> .
   ?var24 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var19 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var20 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var11 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var10 .
   ?var18 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasParent> ?var16 .
   ?var5 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var14 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var5 .
   ?var20 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var15 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var6 .
   ?var7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var23 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var12 <https://glyconnect.expasy.org/rdf/structures#composition> "Hex"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var17 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var8 .
   ?var14 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var8 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var15 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var22 .
   ?var2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var18 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var9 .
   ?var7 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var3 <https://glyconnect.expasy.org/rdf/structures#baseName> "dman-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Residue> .
   ?var17 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var15 <https://glyconnect.expasy.org/rdf/structures#composition> "HexNAc"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var18 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var24 .
   ?var4 <https://glyconnect.expasy.org/rdf/structures#baseName> "dman-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Substituent> .
   ?var11 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var20 .
   ?var17 <https://glyconnect.expasy.org/rdf/structures#hasSubstituent> ?var23 .
   ?var20 <https://glyconnect.expasy.org/rdf/structures#subAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var19 <https://glyconnect.expasy.org/rdf/structures#subParentAnomerConnection> "2"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var2 <https://glyconnect.expasy.org/rdf/structures#baseAnomerConnection> "1"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var11 <https://archive.org/services/purl/domain/modular_ontology_design_library/treehasChild> ?var12 .
   ?var2 <https://glyconnect.expasy.org/rdf/structures#baseName> "dglc-HEX-1:5"^^<http://www.w3.org/2001/XMLSchema#string> .
   ?var3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://glyconnect.expasy.org/rdf/structures#Base> .
   ?var12 <https://glyconnect.expasy.org/rdf/structures#hasBase> ?var3 .
   ?var24 <https://glyconnect.expasy.org/rdf/structures#subName> "n-acetyl"^^<http://www.w3.org/2001/XMLSchema#string> .
   FILTER (?var11 != ?var12)
   FILTER (?var11 != ?var13)
   FILTER (?var11 != ?var14)
   FILTER (?var11 != ?var15)
   FILTER (?var11 != ?var16)
   FILTER (?var11 != ?var17)
   FILTER (?var11 != ?var18)
   FILTER (?var11 != ?var10)
   FILTER (?var12 != ?var13)
   FILTER (?var12 != ?var14)
   FILTER (?var12 != ?var15)
   FILTER (?var12 != ?var16)
   FILTER (?var12 != ?var17)
   FILTER (?var12 != ?var18)
   FILTER (?var12 != ?var10)
   FILTER (?var13 != ?var14)
   FILTER (?var13 != ?var15)
   FILTER (?var13 != ?var16)
   FILTER (?var13 != ?var17)
   FILTER (?var13 != ?var18)
   FILTER (?var13 != ?var10)
   FILTER (?var14 != ?var15)
   FILTER (?var14 != ?var16)
   FILTER (?var14 != ?var17)
   FILTER (?var14 != ?var18)
   FILTER (?var14 != ?var10)
   FILTER (?var15 != ?var16)
   FILTER (?var15 != ?var17)
   FILTER (?var15 != ?var18)
   FILTER (?var15 != ?var10)
   FILTER (?var16 != ?var17)
   FILTER (?var16 != ?var18)
   FILTER (?var16 != ?var10)
   FILTER (?var17 != ?var18)
   FILTER (?var17 != ?var10)
   FILTER (?var18 != ?var10)
   FILTER NOT EXISTS {?glycanbag <https://glyconnect.expasy.org/rdf/structures#hasItemRoot> ?var10}
}
GROUP BY ?glycanid
ORDER BY ASC(xsd:integer(?glycanid))
