#title: Count structures glycancore
#comment: Count of all structures that have associated GlycanCore % Query 3.14 (b)

PREFIX glystreem: <https://glyconnect.expasy.org/rdf/structures#>

select (count (distinct ?glycanid) as ?countid ) WHERE
{
    ?glycan a glystreem:Glycan ;
        glystreem:id ?glycanid ;
        glystreem:hasGlycanCore ?glycancore .
    ?glycancore a glystreem:GlycanCore .
}
