#title: Count structures residue root
#comment: Count of all structures that have associated ResidueRoot % Query 3.14 (c)

PREFIX glystreem: <https://glyconnect.expasy.org/rdf/structures#>

select (count (distinct ?glycanid) as ?countid ) WHERE
{
    ?glycan a glystreem:Glycan ;
    glystreem:id ?glycanid ;
    glystreem:hasGlycanCore ?glycancore .
    ?glycancore a glystreem:GlycanCore ;
        glystreem:hasCoreRoot ?coreroot .
    ?coreroot a glystreem:ResidueRoot .
}
